[WARNING] Exception of type java.lang.Exception occurred in online testing but java.io.IOException occurred now.
[WARNING] Ignoring different exception occurrence in offline test.
[WARNING] The remaining test execution may produce different results.
[ERROR] java.io.IOException: Test
[ERROR] 	at modbat.test.MockExcEnv$.nonDetCall(MockExcEnv.scala)
[ERROR] 	at modbat.test.ExcTest4$$anonfun$1.apply$mcV$sp(ExcTest4.scala)
[ERROR] 	at modbat.test.ExcTest4$$anonfun$1.apply(ExcTest4.scala)
[ERROR] 	at modbat.test.ExcTest4$$anonfun$1.apply(ExcTest4.scala)
[WARNING] java.lang.AssertionError: assertion failed occurred, aborting.
[ERROR] java.lang.AssertionError: assertion failed
[ERROR] 	at scala.Predef$.assert(Predef.scala)
[ERROR] 	at modbat.dsl.Model$.assert(Model.scala)
[ERROR] 	at modbat.dsl.Model$class.assert(Model.scala)
[ERROR] 	at modbat.test.ExcTest4.assert(ExcTest4.scala)
[ERROR] 	at modbat.test.ExcTest4$$anonfun$2.apply$mcV$sp(ExcTest4.scala)
[ERROR] 	at modbat.test.ExcTest4$$anonfun$2.apply(ExcTest4.scala)
[ERROR] 	at modbat.test.ExcTest4$$anonfun$2.apply(ExcTest4.scala)
