Result of call is false.
Offline mode: not throwing exception.
err1
